theme = "base16"

[editor]
auto-pairs = false
color-modes = true
cursorcolumn = true
cursorline = true
end-of-line-diagnostics = "hint"
middle-click-paste = false
mouse = false
popup-border = "popup"
rulers = [60, 80, 100, 120]

[editor.lsp]
display-inlay-hints = true
display-messages = true
goto-reference-include-declaration = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false
git-exclude = false

[editor.whitespace.render]
space = "all"
nbsb = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "‚ñè"
skip-levels = 1

[editor.smart-tab]
enable = false

[editor.inline-diagnostics]
cursor-line = "info"

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"

W = "extend_next_word_start"
"A-w" = "move_next_long_word_start"
"A-W" = "extend_next_long_word_start"
B = "extend_prev_word_start"
"A-b" = "move_prev_long_word_start"
"A-B" = "extend_prev_long_word_start"
E = "extend_next_word_end"
"A-e" = "move_next_long_word_end"
"A-E" = "extend_next_long_word_end"

g = { "k" = "goto_file_start", "j" = "goto_last_line" }

"A-h" = "goto_line_start"
"A-H" = "extend_to_line_start"
"A-l" = "goto_line_end"
"A-L" = "extend_to_line_end"

"A-f" = "find_prev_char"
"A-t" = "till_prev_char"
"F" = "extend_next_char"
"T" = "extend_till_char"
"A-F" = "extend_prev_char"
"A-T" = "extend_till_prev_char"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

"X" = "extend_line"
"A-x" = "extend_to_line_bounds"

"A-j" = "join_selections"

"A-ret" = "vsplit"

"C-s" = ":write"

"C-/" = "toggle_comments"

"N" = "extend_search_next"
"A-N" = "extend_search_prev"
"A-n" = "search_prev"

"m" = "match_brackets"
"M" = ["select_mode", "match_brackets", "normal_mode"]

[keys.select]
g = { "k" = "goto_file_start", "j" = "goto_last_line" }

[keys.insert]
"C-space" = "completion"
